name: Next.js CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lintTest:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          echo "Installing dependencies..."
          npm install
      - name: Run Linting
        run: |
          echo "Running linting..."
          npm run lint
        env:
          CI: true

  securityCheck:
    name: Security Check
    runs-on: ubuntu-latest
    steps:
      - name: Check for security
        run: |
          echo "Run security checks..."
          sleep 5
          echo "Run security checks 1..."
          sleep 5
          echo "Run security checks 2..."
          sleep 5
          echo "Run security checks 3..."
          sleep 5
  build-and-deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: 20.x

      - name: Install Dependencies
        run: yarn install
      - name: Deploy to Vercel
        run: vercel --prod --token ${{ 'qzdzRWYgmOBVQnCZfjURbsxR' }}
